paths:
    snapshot_file: /path/to/snapshot/file
    results_directory: /path/to/the/directory
    density_field_file: null
grid:
    size: 256
density_field:
    create: true
    smooth: true
    smoothing_scales:
      - 0.0
      - 1.0
      - 3.0
calculations:
    potential_field: true
    traceless_tidal_tensor: true
